DOMAIN = "windguru"

DEFAULT_SCAN_INTERVAL = 300
MIN_SCAN_INTERVAL = 60

API_BASE = "https://www.windguru.cz/int/iapi.php"
API_REFERER = "https://www.windguru.cz/station/{station_id}"

SENSOR_TYPES = {
    "wind_avg": {
        "name": "Wind Average",
        "unit": "kn",
        "icon": "mdi:weather-windy",
        "device_class": "wind_speed",
        "state_class": "measurement",
    },
    "wind_max": {
        "name": "Wind Gust",
        "unit": "kn",
        "icon": "mdi:weather-windy",
        "device_class": "wind_speed",
        "state_class": "measurement",
    },
    "wind_min": {
        "name": "Wind Min",
        "unit": "kn",
        "icon": "mdi:weather-windy",
        "device_class": "wind_speed",
        "state_class": "measurement",
    },
    "wind_direction": {
        "name": "Wind Direction",
        "unit": "°",
        "icon": "mdi:compass-rose",
        "device_class": None,
        "state_class": None,
    },
    "temperature": {
        "name": "Temperature",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "mslp": {
        "name": "Pressure",
        "unit": "hPa",
        "icon": "mdi:gauge",
        "device_class": "pressure",
        "state_class": "measurement",
    },
    "rh": {
        "name": "Humidity",
        "unit": "%",
        "icon": "mdi:water-percent",
        "device_class": "humidity",
        "state_class": "measurement",
    },
}

COUNTRY_TIMEZONES = {
    380: ["Europe/Rome"],
    250: ["Europe/Paris"],
    276: ["Europe/Berlin"],
    724: ["Europe/Madrid"],
    620: ["Europe/Lisbon"],
    826: ["Europe/London"],
    300: ["Europe/Athens"],
    528: ["Europe/Amsterdam"],
    56: ["Europe/Brussels"],
    756: ["Europe/Zurich"],
    40: ["Europe/Vienna"],
    208: ["Europe/Copenhagen"],
    752: ["Europe/Stockholm"],
    578: ["Europe/Oslo"],
    246: ["Europe/Helsinki"],
    616: ["Europe/Warsaw"],
    203: ["Europe/Prague"],
    703: ["Europe/Bratislava"],
    348: ["Europe/Budapest"],
    705: ["Europe/Ljubljana"],
    191: ["Europe/Zagreb"],
    688: ["Europe/Belgrade"],
    100: ["Europe/Sofia"],
    642: ["Europe/Bucharest"],
    804: ["Europe/Kyiv"],
    643: ["Europe/Moscow", "Europe/Kaliningrad"],
    792: ["Europe/Istanbul"],
    840: ["America/New_York", "America/Chicago", "America/Denver", "America/Los_Angeles", "America/Anchorage", "Pacific/Honolulu"],
    124: ["America/Toronto", "America/Vancouver", "America/Winnipeg", "America/Halifax", "America/St_Johns"],
    36: ["Australia/Sydney", "Australia/Melbourne", "Australia/Perth", "Australia/Brisbane", "Australia/Adelaide", "Australia/Hobart", "Australia/Darwin"],
    554: ["Pacific/Auckland", "Pacific/Chatham"],
    76: ["America/Sao_Paulo", "America/Fortaleza", "America/Manaus"],
    32: ["America/Argentina/Buenos_Aires"],
    152: ["America/Santiago"],
    484: ["America/Mexico_City", "America/Tijuana", "America/Cancun"],
    392: ["Asia/Tokyo"],
    356: ["Asia/Kolkata"],
    702: ["Asia/Singapore"],
    360: ["Asia/Jakarta"],
    764: ["Asia/Bangkok"],
    704: ["Asia/Ho_Chi_Minh"],
    608: ["Asia/Manila"],
    410: ["Asia/Seoul"],
    158: ["Asia/Taipei"],
    344: ["Asia/Hong_Kong"],
    784: ["Asia/Dubai"],
    682: ["Asia/Riyadh"],
    376: ["Asia/Jerusalem"],
    400: ["Asia/Amman"],
    422: ["Asia/Beirut"],
    196: ["Asia/Nicosia"],
    818: ["Africa/Cairo"],
    504: ["Africa/Casablanca"],
    710: ["Africa/Johannesburg"],
    716: ["Africa/Harare"],
    566: ["Africa/Lagos"],
    894: ["Africa/Lusaka"],
    508: ["Africa/Maputo"],
    480: ["Indian/Mauritius"],
    638: ["Indian/Reunion"],
    540: ["Pacific/Noumea"],
    258: ["Pacific/Tahiti"],
    242: ["Pacific/Fiji"],
    584: ["Pacific/Kwajalein"],
    296: ["Pacific/Tarawa"],
}
